# Generated by Django 3.2 on 2021-05-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0003_alter_custom_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_group',
            old_name='desciption',
            new_name='description',
        ),
    ]
