# Generated by Django 3.2 on 2021-05-03 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODO_list', '0005_auto_20210503_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acces',
            new_name='Access',
        ),
    ]
