# Generated by Django 3.2 on 2021-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0006_rename_acces_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': 'Access'},
        ),
    ]
