# Generated by Django 3.2 on 2021-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_list', '0007_alter_access_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
